services:
  api:
    build: .
    ports:
      - 8000:8000 
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    ports:
     - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  
  redis:
    image: redis:6
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379

volumes:
  db-data: