services:
  api:
    build: .
    restart: on-failure
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE=${ACCESS_TOKEN_EXPIRE}
      - REFRESH_TOKEN_EXPIRE=${REFRESH_TOKEN_EXPIRE}
      - JTI_BLOCKLIST_URL=${JTI_BLOCKLIST_URL}
    depends_on:
      - db
      - jti_blocklist

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
    ports:
     - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  
  jti_blocklist:
    image: redis:6
    ports:
      - 6379:6379
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - api


volumes:
  db-data:
