services:
  api:
    build: .
    restart: on-failure
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE=${ACCESS_TOKEN_EXPIRE}
      - REFRESH_TOKEN_EXPIRE=${REFRESH_TOKEN_EXPIRE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    ports:
     - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  
  redis:
    image: redis:6
    ports:
      - ${REDIS_PORT}:6379
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - api
    

volumes:
  db-data:
