name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Docker Compose
      run: sudo apt-get install docker-compose
    - name: Build and run containers with Docker Compose
      env:
        DB_NAME: ${{ vars.DB_NAME }}
        DB_HOST: ${{ vars.DB_HOST }}
        DB_PORT: ${{ vars.DB_PORT }}
        DB_USER: ${{ vars.DB_USER }}
        DB_USER_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        ACCESS_TOKEN_EXPIRE: ${{ vars.ACCESS_TOKEN_EXPIRE }}
        REFRESH_TOKEN_EXPIRE: ${{ vars.REFRESH_TOKEN_EXPIRE }}
        REDIS_HOST: ${{ vars.REDIS_HOST }}
        REDIS_PORT: ${{ vars.REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      run: docker compose up --build
